### ISSUE TITLE
Failure With Other Dockets

### ISSUE THREAD

**Issue by nliftman** [q-w-a/regulationsgov#8]
If you use any other docketId, other than the one given, the system fails to get the comments. Resulting in the error shown in the screenshot below. 

<img width="713" alt="Screen Shot 2022-06-06 at 3 26 13 PM" src="https://user-images.githubusercontent.com/90527738/172233351-ac5625dc-9ead-4777-aecd-d9e6a20b7f45.png">

**Comment by q-w-a** [comment]
Hi Naomi,

"https://www.regulations.gov/document/FEMA-2008-0005-0022" is the documentId, not the docketId. The syntax should be:

`comments <- regulationsgov::get_all_comments(endpoint = "document", documentId = "FEMA-2008-0005-0022")`.

You can see which kind of ID it is at [regulations.gov](https://www.regulations.gov/document/FEMA-2008-0005-0022).

**Comment by nliftman** [comment]
Awesome thank you for your help!
